Translated Readme file to Hebrew
huggingface/education-toolkit pull request #19
Opened 2022-03-13 12:11 UTC by omer-dor

2022-03-19 00:16 UTC, omarespejel commented
Thanks @omer-dor!

2022-03-23 19:44 UTC, omarespejel requested changes
Thank you @omer-dor! Only some nits.

2022-03-23 19:44 UTC, omarespejel commented on tutorials/HEB/01_huggingface-hub-tour.md
> +# Workshop: A Tour through the Hugging Face Hub
I think we can eliminate this file until we have a Hebrew translation.

2022-03-23 19:44 UTC, omarespejel commented on tutorials/HEB/02_ml-demos-with-gradio.ipynb
> +{
We can also eliminate this document until we have the Hebrew translation.

2022-03-23 19:44 UTC, omarespejel commented on tutorials/HEB/03_getting-started-with-transformers.ipynb
> +{
We can also eliminate this document until we have the Hebrew translation.

2022-03-24 19:39 UTC, omer-dor commented
@omarespejel I deleted the files you requested, I will translate them also next week and create another PR.

2022-03-25 22:02 UTC, omarespejel approved these changes
This is great! Thanks 🤗

2022-03-25 22:02 UTC, merged

2022-03-25 22:03 UTC, omarespejel commented
Merged. Thanks! Please let me know if you need anything.